### ISSUE TITLE
On Mediawiki 1.26 Mainpage changes to PlantUML github page when installing this extension

### ISSUE THREAD

**Issue by indra-balicasa** [pjkersten/PlantUML#10]
Hallo, is it still support for mediawiki extensions?

**Comment by izacaslo** [comment]
@pjkersten I used to use PlantUML at Eclipse. It is perfect :) Now, I just installed MediaWiki v1.26 exclusively to use with PlantUML extension. Everytime I put "require_once('extensions/PlantUML/PlantUML.php');" on my LocalSettings.php file, my mediawiki/main_page changes to PlantUML github page. Is it working ok?

**Comment by WolfgangFahl** [comment]
Did you install plantuml.jar or does this only happen in the cloud setup?

**Comment by WolfgangFahl** [comment]
In the meantime MW 1.26 is end of life so i am closing this issue.
