### ISSUE TITLE
Promote this on English Wikipedia

### ISSUE THREAD

**Issue by PanderMusubi** [pjkersten/PlantUML#11]
Promote this on English Wikipedia with an article on PlantUML and plugin.

Also request Wikipedia to activitate this plugin as a standard service in their articles.

**Comment by WolfgangFahl** [comment]
I have added the MediaWiki plugin notice to the mainpage. Asking The Wikimedia Foundation to use this is something you might want to do thru the MediaWiki Stakeholer's Group https://www.mediawiki.org/wiki/MediaWiki_Stakeholders'_Group
