### ISSUE TITLE
Extension not working after upgrade to Ubuntu 10.4.2 and Mediawiki 1.24.1

### ISSUE THREAD

**Issue by rosch100** [pjkersten/PlantUML#13]
After upgrading Ubuntu and MediaWiki, I received the error: [An error occured in PlantUML extension].
How could I nail down the issue?

**Comment by mbeauv** [comment]
You can reproduce this problem using the mediawiki vagrant box:

https://www.mediawiki.org/wiki/MediaWiki-Vagrant

(When I got this problem the vagrant box was using Ubuntu 14.04)

**Comment by izacaslo** [comment]
@rosch100 , I just installed MediaWiki v1.26 exclusively to use with PlantUML extension. Everytime I put "require_once('extensions/PlantUML/PlantUML.php');" on my LocalSettings.php file, my mediawiki/main_page changes to PlantUML github page. Is it working ok for you?

**Comment by WolfgangFahl** [comment]
As of version 0.5 / 0.6 the error "An error occured in PlantUML extension"  is displayed when the cache handling of PlantUML fails.  To improve this error message please supply more information on what your circumstances are.
