### ISSUE TITLE
MediaWiki-Plugin does not understand "salt" diagrams

### ISSUE THREAD

**Issue by mbrinkma** [pjkersten/PlantUML#16]
I tried to create a wiki page like this:

<uml>
salt
{
  Just plain text
  [This is my button]()  Unchecked radio
  (X) Checked radio
  []  Unchecked box
  [X] Checked box
  "Enter text here   "
  ^This is a droplist^
}
</uml>

But I get a rendering which displays an error:

[From ... (line 3) ]
@startuml

salt
Forbidden line salt

**Comment by WolfgangFahl** [comment]
Looks like you missed the `<uml></uml>` tags. See:

http://wiki.bitplan.com/index.php/PlantUML_salt_diagram_example
