### ISSUE TITLE
plantuml jar filename change

### ISSUE THREAD

**Issue by nkorber** [pjkersten/PlantUML#25]
Hello, 
with the version 8059 the name of the jar file is now plantuml-8059.jar. As I guess this name will evolve, I propose the following initialisation in PlantUml.php (of course the exact path is for my installation...)

$plantumlJar = exec("ls /var/lib/tomcat/webapps/plantuml/WEB-INF/lib/plantuml*.jar");

greetings
Nicolas

**Comment by WolfgangFahl** [comment]
`curl -L http://sourceforge.net/projects/plantuml/files/plantuml.jar/download -o plantuml.jar `
will download the latest plantuml.jar as plantuml.jar for you
