### ISSUE TITLE
Error on extension notation in forms

### ISSUE THREAD

**Issue by megankatsumi** [pjkersten/PlantUML#31]
I'm unable to use PlantUML notation to create a diagram with the extension notation using a form. Other PlantUML diagrams work via the form, but the <|--  results in the following error:
`"|" is not allowed, except within {{...}}, [[...]], or special tags`

I would expect that this should work as the "|" symbol is defined within the <uml> tag. Any pointers on this? Is there some alternate notation that I can substitute?

**Comment by WolfgangFahl** [comment]
Thx for opening this issue. Could please give a bit more context regarding your Mediawiki environment? Which version are you using what do you mean by "using a form". Yes | is a special character thats why there is a {{!}} Template which might be useful in your context. This is not specific to this extension.

**Comment by megankatsumi** [comment]
Right, sorry about that. I'm using Mediawiki 1.33.1, along with [PageForms 4.6](https://www.mediawiki.org/wiki/Extension:Page_Forms) and [UML 0.7](https://www.mediawiki.org/wiki/Extension:PlantUML).
As an example, I'm trying to allow for PlantUML input in a form (e.g. text area input). This works for some diagrams, but not for example if I wanted to add:
```
<uml>
Class01 <|-- Class02
</uml>
```
The {{!}} template does not work in this case as it is read as syntax error by PlantUML.

**Comment by WolfgangFahl** [comment]
You might want to discuss the issue with Yaron Koren - he's the author of PageForms and it looks like the code you input in the form doesn't make it unspoiled to the PlantUML extension. See http://wiki.bitplan.com/index.php/PlantUML_Issue_31 for an example how the plantuml extension has no issue with your code.
