### ISSUE TITLE
dedicated plantuml instance (usecloud=true) behind a proxy

### ISSUE THREAD

**Issue by boly38** [pjkersten/PlantUML#8]
Hi, 
 for your information, i just release a quick patch wich allow setting a proxy while getting plantuml generated image in cloud mode. 

I document it here : http://www.mediawiki.org/wiki/Extension_talk:PlantUML#PlantUML_with_a_dedicated_plantuml_server_behind_proxy

maybe you could include this option into your next release? ;)

anyway, thanks for this useful extension.
regards
 Boly38

**Comment by boly38** [comment]
But who is Boly31 ? ;)

**Comment by WolfgangFahl** [comment]
:-) Could you please test the merged version 0.6 in you environment? I removed the hardcoded proxy setting but it should still work if the proy is set in the ENV

**Comment by boly38** [comment]
@WolfgangFahl sorry, but my environment has changed, I have no way to test that today. :(
